# Generated by Django 3.2 on 2021-12-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advent_calendar', '0002_alter_adventcalendar_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
