# Generated by Django 3.2 on 2021-12-11 14:39

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('ingredients', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None)),
                ('method', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None)),
            ],
        ),
    ]
